40 fix/add test for remove tags
sudar/bulk-move pull request #58
Opened 2017-12-30 07:12 UTC by anandB000

2017-12-31 09:48 UTC, sudar requested changes

2017-12-31 09:48 UTC, sudar commented on tests/wp-tests/BM/Metabox/Posts/TagTest.php
> +        // Create two tags and a common tag.
Alignment is wrong. Make sure you are using tabs with 4 spaces for indent.

2018-01-02 17:34 UTC, anandB000 commented on tests/wp-tests/BM/Metabox/Posts/TagTest.php
> +        // Create two tags and a common tag.
Fixed

2018-01-03 16:47 UTC, sudar approved these changes

2018-01-03 16:47 UTC, merged