80 fix/scrutinizer js errors
sudar/bulk-move pull request #88
Opened 2018-02-24 07:30 UTC by mariadanieldeepak

Fix #80

2018-02-26 05:20 UTC, sudar requested changes

2018-02-26 05:20 UTC, sudar commented on assets/js/src/bulk-move.js
> +            return;
We don't need to add empty `return` statements.

2018-02-26 05:20 UTC, sudar commented on include/Page/Base.php
> +		wp_enqueue_script( 'bulk-move', $this->get_plugin_dir_url() . 'assets/js/src/bulk-move.js', array( 'jquery', 'postbox' ), BM_BulkMove::VERSION, true );
We should include the js file from the `assets/js/` folder not from `src` folder.

We will have a build step (similar to Bulk Delete) where we will contact and compress files from `assets/js/src` folder into `assets/js` folder.

2018-03-03 03:20 UTC, mariadanieldeepak commented on assets/js/src/bulk-move.js
> +            return;
@sudar,

 > We don't need to add empty return statements.

I added it after reading Scrutinizer's comments. I'll remove it as it doesn't add value.

2018-03-03 03:26 UTC, mariadanieldeepak commented on include/Page/Base.php
> +		wp_enqueue_script( 'bulk-move', $this->get_plugin_dir_url() . 'assets/js/src/bulk-move.js', array( 'jquery', 'postbox' ), BM_BulkMove::VERSION, true );
@sudar,

> We will have a build step (similar to Bulk Delete) where we will contact and compress files from assets/js/src folder into assets/js folder.

In this case, can we reference the minified file than the actual JS file? We minify it anyway.

2018-03-03 03:27 UTC, mariadanieldeepak commented
@sudar,

Please note that the Scrutinizer would fail again asking for the explicit `return` statements.

2018-03-03 05:27 UTC, sudar approved these changes

2018-03-03 05:27 UTC, merged